let cadena='Hola Mundo';
console.log(cadena.length);
console.log(cadena.toUpperCase());
console.log(cadena.toLowerCase());
console.log(cadena.indexOf('o'));
console.log(cadena.indexOf('Hola'));
console.log(cadena.replace('Mundo','Youtube'));
console.log(cadena.substring(4));
console.log(cadena.includes('H'));
console.log(cadena.includes('h'));
console.log('r'.repeat(10));
let nombre='Joseba';
let apellidos='Diaz';
let edad='20';
console.log(`Hola ${nombre} ${apellidos}. Tienes ${edad} anos`);